### ISSUE TITLE
Race between getKeyJSONdataAndCleanKeys in running functions and release pipeline executions may lead when under load to wrong deletion of the just created key

### ISSUE THREAD

**Issue by MarcFundenberger** [BrunoReboul/ram#52]
This issue does not only occur on a race.
It also occurs systematically in a multi org scenario, as multiple cloud functions (one per org) are deployed a different times on the sme service account (one per micro services). So the service account key used by the first deployed cloud function is killed by the second etc ..

**Comment by BrunoReboul** [comment]
`getKeyJSONdataAndCleanKeys`
 is called by `getJWTConfigAndCleanKeys`
is called by `GetClientOptionAndCleanKeys`
is called by 4 microservice
- convertlog2feed
- getgroupsettings
- listgroupmembers
- listgroup
